POST http://localhost:4000/email HTTP/1.1
content-type: application/json

{
    "to": "geo.pertea@gmail.com",
    "from": "webapps@libd.org",
    "subject": "post test from gryzen/dev",
    "msg":" let's see if this is working!"

}


